##
# One-shot pod to import a KeyCloak dump into a cluster.
# Expects dump.json to be mounted at /export
#
# kubectl --context=rcc-k8s-prod -nkeycloak apply -f import.yaml
#
# NB: Make sure firewall rules allow LDAP/AD access, it will hang the entire cluster and crash
# during the import otherwise.
##
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-import-scripts
data:
  # https://keycloak.discourse.group/t/keycloak-timeout-issue/2309
  10-fix-timeout.cli: |
    embed-server --server-config=standalone.xml --std-out=echo
    echo Changing transaction default timeout
    /subsystem=transactions/:write-attribute(name=default-timeout,value=86400)
    echo Done
    stop-embedded-server
  20-fix-timeout-ha.cli: |
    embed-server --server-config=standalone-ha.xml --std-out=echo
    echo Changing transaction default timeout
    /subsystem=transactions/:write-attribute(name=default-timeout,value=86400)
    echo Done
    stop-embedded-server
---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-import
  labels:
    app: keycloak
spec:
  nodeName: prod-worker-06
  volumes:
    - name: kcdump
      hostPath:
        path: /home/ubuntu/kc
        type: Directory
    - name: startup-scripts
      configMap:
        name: keycloak-import-scripts
  containers:
  - name: keycloak
    image: uqrcc/keycloak-rcc:15.0.2
    env:
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: keycloak-db
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER
      value: keycloak
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-db-password
          optional: false
    - name: KEYCLOAK_FRONTEND_URL
      value: https://keycloak.prod.rcc-k8s.cloud.edu.au/auth
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: keycloak-admin-credentials
          optional: false
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-admin-credentials
          optional: false
    - name: JAVA_OPTS_APPEND
      value: >
        -Dkeycloak.profile.feature.docker=enabled
        -Dkeycloak.migration.action=import
        -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
        -Dkeycloak.migration.provider=singleFile
        -Dkeycloak.migration.file=/export/dump.json
        -Djboss.as.management.blocking.timeout=86400
    - name: JGROUPS_DISCOVERY_PROTOCOL
      value: kubernetes.KUBE_PING
    - name: JGROUPS_DISCOVERY_PROPERTIES
      value: port_range=0,dump_requests=false
    - name: KUBERNETES_NAMESPACE
      value: keycloak
    - name: KUBERNETES_LABELS
      value: app=keycloak
    volumeMounts:
      - mountPath: /export
        name: kcdump
      - mountPath: /opt/jboss/startup-scripts
        name: startup-scripts
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  automountServiceAccountToken: true
  serviceAccount: keycloak-kubeping-service-account
  serviceAccountName: keycloak-kubeping-service-account

